[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
rand_distr = "0.5.1"
argmin = { version = "0.10.0" }
ndarray = "0.16.1"
eframe = "0.31.1"
egui = "0.31.1"
egui_plot = "0.32.1"